# Created with Komac v1.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: VGN.VHUB
PackageVersion: 2.3.17
Platform:
- Windows.Desktop
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
AppsAndFeaturesEntries:
- InstallerType: nullsoft
Installers:
- Architecture: x64
  InstallerUrl: https://cdn.vgnclub.com/device/download/win32/2.3.17/v-device-1-2.3.17.exe
  InstallerSha256: 8A0EF02340A15FE1274AC1E537253D479138764021FF4852E227C60781F32000
ManifestType: installer
ManifestVersion: 1.5.0
