# Created with Komac v1.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: GyulyVGC.Sniffnet
PackageVersion: 1.2.2
PackageLocale: en-US
Publisher: Giuliano Bellini
PublisherUrl: https://github.com/GyulyVGC
PublisherSupportUrl: https://github.com/GyulyVGC/sniffnet/issues
Author: Giuliano Bellini
PackageName: Sniffnet
PackageUrl: https://github.com/GyulyVGC/sniffnet
License: APACHE-2.0
LicenseUrl: https://github.com/GyulyVGC/sniffnet/blob/main/LICENSE-APACHE
CopyrightUrl: https://github.com/GyulyVGC/sniffnet/blob/main/LICENSE-APACHE
ShortDescription: Sniffnet is the application to comfortably monitor your Internet traffic.
Moniker: sniffnet
ReleaseNotes: |-
  New features
  - Added new application themes: _Dracula_, _Gruvbox_, _Nord_, and _Solarized_ (#330)
  - Themes are based on well-known and established color palettes maintained by dedicated organisations
  - Each theme comes with a light and a dark variant, for a total of 8 new color schemes
  - Added option to set different shades of color gradients for each of the available themes
  - Added Finnish translation 🇫🇮 (#310)
  - Added support for --help and --version command line arguments (#272)
  Improvements
  - Migrated to Iced 0.10, that is now able to select the graphical renderer at runtime: a fallback one (tiny-skia) will be used in case the default one (wgpu) crashes (#324)
  - General aesthetic improvements (see #119 for more info):
  - redesigned page tabs
  - highlighted headings with different colors
  - simplified scrollables' style
  - improvements to Deep Sea and Mon Amour color palettes
  - Restructured issue templates to let users open issues in a more efficient and effective way (#285)
  - Updated French translation to v1.2 (#279)
  - Color palettes in settings page are now built as Rule widgets, without involving the use of external SVGs anymore
  Fixes
  - Fixed alt+tab shortcut issue (#298 — fixes #262)
  - Added app id in order to correctly show the icon and app name on Linux Wayland (fixes #292)
  - Fixed problem that didn't allow opening links and the report file on operating systems different from Windows, macOS, and Linux
  - Use scrollable to make active filters visible when the selected adapter name is long (overview page)
  - Ensure no colored pixel is shown if the respective packets or bytes number is zero
  - Minor fix to Chinese translation (#271)
  Thanks to:
  - @ZEROF, @0x0177b11f, @cthulu201, @wahn for sponsoring Sniffnet 💖
  - @joshuamegnauth54 for having helped to set up the new themes
  - @vtiinanen for Finnish translation
  - @Aloso for having added --help and --version command line arguments
  - @starccy for having fixed alt + tab shortcut issue
  - @Digitalone1 for having helped to troubleshoot icon visibility problems on Wayland
  - @Quetzal-coalt for updating French translation to v1.2
  - @wangzishi for a fix to Chinese translation
ReleaseNotesUrl: https://github.com/GyulyVGC/sniffnet/releases/tag/v1.2.2
ManifestType: defaultLocale
ManifestVersion: 1.5.0
